[profile.default]
src = "src"
ast = true
out = "out"
libs = ["lib"]
build_info = true
extra_output = ["storageLayout"]
ffi = true

remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    '@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts',
    "abdk-libraries-solidity=lib/abdk-libraries-solidity",
    "openzeppelin-foundry-upgrades/=lib/openzeppelin-foundry-upgrades/src/"
]

fs_permissions = [{ access = "read", path = "./broadcast" },{ access = "read", path = "./out" }]


[etherscan]
dbc-testnet = { key = "abc", url = "https://rpc-testnet.dbcwallet.io", chain = "19850818" }


[rpc_endpoints]
dbc-testnet = "https://rpc-testnet.dbcwallet.io"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
